import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { ReduxProvider } from "@/redux/features/provider";
import imageCart from "@/app/opengraph-image.png";
import NavBar from "./NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: {
    default: "Next-Redux",
    template: "%s - дочерняя страница ",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
           <NavBar/>
          <Image className="image_Poshta" src={imageCart}
            alt="Электронная почта"/>       
          <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
